### ISSUE TITLE
Not working on GLPI 0.90.3 C

### ISSUE THREAD

**Issue by ychoucha** [pluginsGLPI/simcard#48] opened 2016-05-10 12:04 UTC
Hello i m using the blue GLPI version GLPI 0.90.3 C
and the simcard plugin not working, 
i have the message : 

	This plugin requires GLPI >= 0.84 and GLPI < 0.85

**Comment by dethegeek** [comment] 2016-05-10 12:09
I think you're using the wring branch. Try 0.85-bugfixes or master. They should both work.

**Comment by ychoucha** [comment] 2016-05-10 13:36
U right with the master branch works !!

can now using fusioninventory from android to import information ?

**Comment by dethegeek** [comment] 2016-05-10 13:40
About simcards, I guess not. Ask on IRC or forum dedicated to FusionInventory about that.

Thanks for your feedback.

I'm closing ticket as the issue is solved.

**Closed by dethegeek** 2016-05-10 13:40 UTC

**Comment by dethegeek** [comment] 2016-05-14 06:54
Hi

Have a look on this : this is a first step to make Simcard and FusionInventory work together 

https://github.com/fusioninventory/fusioninventory-for-glpi/pull/1795/commits/a437540b69019c986f3e5500ed4590cc68fb97f5
